"""auth

Revision ID: 7fcb95e25f3b
Revises: fd6545dc025d
Create Date: 2025-04-09 21:02:45.375889

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "7fcb95e25f3b"  # pragma: allowlist secret
down_revision: Union[str, None] = "fd6545dc025d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "name", sa.Enum("admin", "user", name="userrolesenum"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "user",
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
    )
    op.add_column("user", sa.Column("role_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_foreign_key(
        None, "user", "role", ["role_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_column("user", "role_id")
    op.drop_column("user", "username")
    op.drop_table("role")
    # ### end Alembic commands ###
