"""auth 1

Revision ID: a5aab7a5cf0e
Revises: 7fcb95e25f3b
Create Date: 2025-04-09 22:59:41.856859

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a5aab7a5cf0e"  # pragma: allowlist secret
down_revision: Union[str, None] = "7fcb95e25f3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "role", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "role", type_="unique")
    # ### end Alembic commands ###
